Automatically reload the integration when extended entity discovery is enabled
custom-components/alexa_media_player pull request #1254
Opened 2021-04-18 04:05 UTC by blm126

As the title says, simplify the experience by auto-reloading. I'll update wiki when this merges.

2021-04-18 21:38 UTC, alandtse requested changes

2021-04-18 21:38 UTC, alandtse commented on custom_components/alexa_media/__init__.py
> +            if key == CONF_EXTENDED_ENTITY_DISCOVERY and new_value:
Shouldn't the reload happen regardless if it changes regardless of value? For example when disabling?

2021-04-18 21:38 UTC, alandtse commented on custom_components/alexa_media/__init__.py
> +            if key == CONF_EXTENDED_ENTITY_DISCOVERY and new_value:
Looking at the code more, new_value is already guaranteed to be non None and a changed value here. It can just be if key == ..

2021-04-18 21:41 UTC, alandtse commented on custom_components/alexa_media/__init__.py
> +            if key == CONF_EXTENDED_ENTITY_DISCOVERY and new_value:
Ok also fixed a big where the key forced the reload prematurely. Please test.

2021-04-19 00:43 UTC, blm126 commented on custom_components/alexa_media/__init__.py
> +            if key == CONF_EXTENDED_ENTITY_DISCOVERY and new_value:
Tested and working well

2021-04-19 01:07 UTC, merged

2021-04-23 18:47 UTC, alandtse commented
I'll plan to take this to release this weekend. Will you have any bandwidth to address issues if they come up?

2021-04-24 03:32 UTC, blm126 commented
Yes, I'll have some time.

2021-04-24 05:36 UTC, alandtse commented
Ok, we're live now. Please watch the issues in the next few days to see if anything pops up. I can't really debug this unfortunately.